# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180201_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='numberOfItems',
        ),
    ]
