# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_products_numberofitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(max_length=18),
        ),
    ]
