# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20180201_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
