# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_products_numberofitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='numberOfItems',
            field=models.PositiveIntegerField(),
        ),
    ]
