# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20180201_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D'),
        ),
    ]
