# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
