# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_products_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_favorite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
