# Generated by Django 2.0 on 2018-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(default=0, on_delete='', related_name='feedbacks', to='employee.products'),
        ),
    ]
