# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='governate',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(default='purchaser', max_length=50),
        ),
    ]
