# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0005_auto_20180205_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
