# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0008_auto_20180205_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purchaser_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='telephoneNumber',
        ),
    ]
