# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0009_auto_20180205_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchaser_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='telephoneNumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
