# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0011_remove_payment_purchaser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchaser_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
