# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopOwner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(max_length=11)),
                ('academic_year', models.CharField(max_length=9)),
            ],
        ),
    ]
