# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopOwner', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
    ]
