# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopOwner', '0003_auto_20180129_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='desc',
            field=models.CharField(default='....', max_length=500),
        ),
    ]
