# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopOwner', '0004_requests_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
