# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopOwner', '0009_requests_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requestOwner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
