# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopOwner', '0010_requests_requestowner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'permissions': (('can_add_request', 'Send request'), ('can_view_request', 'view request'))},
        ),
    ]
