# Generated by Django 2.0 on 2018-02-04 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopOwner', '0011_auto_20180204_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requestOwner',
            field=models.ForeignKey(default=0, on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
