# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartpage', '0002_cartproducts_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='cartOwner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
