# Generated by Django 2.0 on 2018-02-04 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpage', '0003_cartproducts_cartowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cartOwner',
            field=models.ForeignKey(default=0, on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
